manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: AYM1607
      url-base: https://github.com/AYM1607

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3  # ğŸ‘ˆ [í•µì‹¬] ì—¬ê¸°ë¥¼ mainì—ì„œ v0.3ìœ¼ë¡œ ë³€ê²½
      import: app/west.yml
    - name: zmk-driver-azoteq-iqs5xx
      remote: AYM1607
      revision: main

  self:
    path: config
